#pragma once

#define META_EXPAND(X) X

#define META_GET_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, NAME, ...) NAME

#define META_FE0(MAC, ...)
#define META_FE1(MAC,  A, B) MAC(A, B)
#define META_FE2(MAC,  A, B, ...) MAC(A, B) META_FE1(MAC,  A, ##__VA_ARGS__)
#define META_FE3(MAC,  A, B, ...) MAC(A, B) META_FE2(MAC,  A, ##__VA_ARGS__)
#define META_FE4(MAC,  A, B, ...) MAC(A, B) META_FE3(MAC,  A, ##__VA_ARGS__)
#define META_FE5(MAC,  A, B, ...) MAC(A, B) META_FE4(MAC,  A, ##__VA_ARGS__)
#define META_FE6(MAC,  A, B, ...) MAC(A, B) META_FE5(MAC,  A, ##__VA_ARGS__)
#define META_FE7(MAC,  A, B, ...) MAC(A, B) META_FE6(MAC,  A, ##__VA_ARGS__)
#define META_FE8(MAC,  A, B, ...) MAC(A, B) META_FE7(MAC,  A, ##__VA_ARGS__)
#define META_FE9(MAC,  A, B, ...) MAC(A, B) META_FE8(MAC,  A, ##__VA_ARGS__)
#define META_FE10(MAC, A, B, ...) MAC(A, B) META_FE9(MAC,  A, ##__VA_ARGS__)
#define META_FE11(MAC, A, B, ...) MAC(A, B) META_FE10(MAC, A, ##__VA_ARGS__)
#define META_FE12(MAC, A, B, ...) MAC(A, B) META_FE11(MAC, A, ##__VA_ARGS__)
#define META_FE13(MAC, A, B, ...) MAC(A, B) META_FE12(MAC, A, ##__VA_ARGS__)
#define META_FE14(MAC, A, B, ...) MAC(A, B) META_FE13(MAC, A, ##__VA_ARGS__)
#define META_FE15(MAC, A, B, ...) MAC(A, B) META_FE14(MAC, A, ##__VA_ARGS__)
#define META_FE16(MAC, A, B, ...) MAC(A, B) META_FE15(MAC, A, ##__VA_ARGS__)
#define META_FE17(MAC, A, B, ...) MAC(A, B) META_FE16(MAC, A, ##__VA_ARGS__)
#define META_FE18(MAC, A, B, ...) MAC(A, B) META_FE17(MAC, A, ##__VA_ARGS__)
#define META_FE19(MAC, A, B, ...) MAC(A, B) META_FE18(MAC, A, ##__VA_ARGS__)
#define META_FE20(MAC, A, B, ...) MAC(A, B) META_FE19(MAC, A, ##__VA_ARGS__)
#define META_FE21(MAC, A, B, ...) MAC(A, B) META_FE20(MAC, A, ##__VA_ARGS__)
#define META_FE22(MAC, A, B, ...) MAC(A, B) META_FE21(MAC, A, ##__VA_ARGS__)
#define META_FE23(MAC, A, B, ...) MAC(A, B) META_FE22(MAC, A, ##__VA_ARGS__)
#define META_FE24(MAC, A, B, ...) MAC(A, B) META_FE23(MAC, A, ##__VA_ARGS__)
#define META_FE25(MAC, A, B, ...) MAC(A, B) META_FE24(MAC, A, ##__VA_ARGS__)
#define META_FE26(MAC, A, B, ...) MAC(A, B) META_FE25(MAC, A, ##__VA_ARGS__)
#define META_FE27(MAC, A, B, ...) MAC(A, B) META_FE26(MAC, A, ##__VA_ARGS__)
#define META_FE28(MAC, A, B, ...) MAC(A, B) META_FE27(MAC, A, ##__VA_ARGS__)
#define META_FE29(MAC, A, B, ...) MAC(A, B) META_FE28(MAC, A, ##__VA_ARGS__)
#define META_FE30(MAC, A, B, ...) MAC(A, B) META_FE29(MAC, A, ##__VA_ARGS__)
#define META_FE31(MAC, A, B, ...) MAC(A, B) META_FE30(MAC, A, ##__VA_ARGS__)
#define META_FE32(MAC, A, B, ...) MAC(A, B) META_FE31(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA2(MAC,  A, B, ...) MAC(A, B), META_FE1(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA3(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA2(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA4(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA3(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA5(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA4(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA6(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA5(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA7(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA6(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA8(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA7(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA9(MAC,  A, B, ...) MAC(A, B), META_FE_COMMA8(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA10(MAC, A, B, ...) MAC(A, B), META_FE_COMMA9(MAC,  A, ##__VA_ARGS__)
#define META_FE_COMMA11(MAC, A, B, ...) MAC(A, B), META_FE_COMMA10(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA12(MAC, A, B, ...) MAC(A, B), META_FE_COMMA11(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA13(MAC, A, B, ...) MAC(A, B), META_FE_COMMA12(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA14(MAC, A, B, ...) MAC(A, B), META_FE_COMMA13(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA15(MAC, A, B, ...) MAC(A, B), META_FE_COMMA14(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA16(MAC, A, B, ...) MAC(A, B), META_FE_COMMA15(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA17(MAC, A, B, ...) MAC(A, B), META_FE_COMMA16(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA18(MAC, A, B, ...) MAC(A, B), META_FE_COMMA17(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA19(MAC, A, B, ...) MAC(A, B), META_FE_COMMA18(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA20(MAC, A, B, ...) MAC(A, B), META_FE_COMMA19(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA21(MAC, A, B, ...) MAC(A, B), META_FE_COMMA20(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA22(MAC, A, B, ...) MAC(A, B), META_FE_COMMA21(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA23(MAC, A, B, ...) MAC(A, B), META_FE_COMMA22(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA24(MAC, A, B, ...) MAC(A, B), META_FE_COMMA23(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA25(MAC, A, B, ...) MAC(A, B), META_FE_COMMA24(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA26(MAC, A, B, ...) MAC(A, B), META_FE_COMMA25(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA27(MAC, A, B, ...) MAC(A, B), META_FE_COMMA26(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA28(MAC, A, B, ...) MAC(A, B), META_FE_COMMA27(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA29(MAC, A, B, ...) MAC(A, B), META_FE_COMMA28(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA30(MAC, A, B, ...) MAC(A, B), META_FE_COMMA29(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA31(MAC, A, B, ...) MAC(A, B), META_FE_COMMA30(MAC, A, ##__VA_ARGS__)
#define META_FE_COMMA32(MAC, A, B, ...) MAC(A, B), META_FE_COMMA31(MAC, A, ##__VA_ARGS__)

#define META_FOREACH_NO_COMMA(MAC, D, ...)    \
   META_GET_NTH_ARG("ignored", ##__VA_ARGS__, \
      META_FE32,META_FE31,META_FE30,META_FE29,META_FE28,META_FE27,META_FE26,META_FE25,META_FE24,META_FE23,META_FE22,META_FE21,META_FE20,META_FE19,META_FE18,META_FE17,META_FE16,META_FE15,META_FE14,META_FE13,META_FE12,META_FE11,META_FE10,META_FE9,META_FE8,META_FE7,META_FE6,META_FE5,META_FE4,META_FE3,META_FE2,META_FE1,META_FE0)(MAC, D, ##__VA_ARGS__)

#define META_FOREACH(MAC, D, ...)             \
   META_GET_NTH_ARG("ignored", ##__VA_ARGS__, \
      META_FE_COMMA32,META_FE_COMMA31,META_FE_COMMA30,META_FE_COMMA29,META_FE_COMMA28,META_FE_COMMA27,META_FE_COMMA26,META_FE_COMMA25,META_FE_COMMA24,META_FE_COMMA23,META_FE_COMMA22,META_FE_COMMA21,META_FE_COMMA20,META_FE_COMMA19,META_FE_COMMA18,META_FE_COMMA17,META_FE_COMMA16,META_FE_COMMA15,META_FE_COMMA14,META_FE_COMMA13,META_FE_COMMA12,META_FE_COMMA11,META_FE_COMMA10,META_FE_COMMA9,META_FE_COMMA8,META_FE_COMMA7,META_FE_COMMA6,META_FE_COMMA5,META_FE_COMMA4,META_FE_COMMA3,META_FE_COMMA2,META_FE1,META_FE0)(MAC, D, ##__VA_ARGS__)

#define META_VA_ARGS_SIZE(...)                        \
   bluegrass::meta::detail::va_args_count_helper(     \
         META_FOREACH(                                \
            META_PASS_STR, "ignored", ##__VA_ARGS__))


